### ISSUE TITLE
Crash in 1.33.0

### ISSUE THREAD

**Issue by pierrebenz** [statsig-io/ios-sdk#6]
Our app is crashing for some of our users using the 1.33.0 release. 

It appears that it's crashing in `StatsigValuesCache.writeToStorage (InternalStore.swift:166)`

I've attached a screenshot to our Sentry report.
 
<img width="1503" alt="Screenshot 2023-11-29 at 10 09 40 AM" src="https://github.com/statsig-io/ios-sdk/assets/204522/177efe11-95aa-4003-84c9-470b76e5aa24">

FYI, it's happening on iOS 15.7.9, 15.8, 16.6.1, 16.7.2.

**Comment by daniel-statsig** [comment]
Hey @pierrebenz, I am investigating a similar crash in 1.33.0 and we don't have a 3.11.0, is this just a typo?

I think this is related to the recent change of writing to the cache on a background thread. I'm trying to nail it down and should have a fix out soon.

That said, this is useful context, if you have any more stack traces please fire them through

**Comment by daniel-statsig** [comment]
@pierrebenz, I have just released 1.33.1. Can you check it out and let me know if it fixes the issue? 

Also, do you have any sense of how frequent the crash was?

**Comment by pierrebenz** [comment]
Hi @daniel-statsig 

Unfortunately, we're still seeing crashes in `1.33.1`. 
<img width="1091" alt="Screenshot 2023-12-05 at 10 58 02 AM" src="https://github.com/statsig-io/ios-sdk/assets/204522/18735e42-147f-45bb-ad46-544e6a173659">


<img width="1114" alt="Screenshot 2023-12-05 at 10 58 40 AM" src="https://github.com/statsig-io/ios-sdk/assets/204522/49cac15d-04ea-4b0b-9b39-3634bc7f6991">

So far, it has affected 88 users.

**Comment by daniel-statsig** [comment]
Thanks for reporting back. Sorry that this wasn't the fix. I will keep looking

**Comment by daniel-statsig** [comment]
@pierrebenz, I have released another version, would you mind giving this one a try?

- https://github.com/statsig-io/ios-sdk/releases/tag/v1.34.0

**Comment by daniel-statsig** [comment]
@pierrebenz was there any updates from your end here? I have been working on more improvements to the threading and just pushed v1.36.0. Are you able to update to https://github.com/statsig-io/ios-sdk/releases/tag/v1.36.0

**Comment by pierrebenz** [comment]
Hi @daniel-statsig. 
We've deployed 1.36.0 in our latest release (`3.304.0`). 
We still saw crashes with the 1.33.1 release (impacting approx. 1.5k users in the last 30 days).So far, not seeing anything suspicious.

**Comment by pierrebenz** [comment]
<img width="1280" alt="Screenshot 2024-02-23 at 11 19 25 AM" src="https://github.com/statsig-io/ios-sdk/assets/204522/08e9a76b-c510-4960-8711-9820e5fc5269">

<img width="1270" alt="Screenshot 2024-02-23 at 11 21 26 AM" src="https://github.com/statsig-io/ios-sdk/assets/204522/4913a45d-2325-4ebd-b8e4-c7d433738bcf">


Looks like we're still seeing crashes even in the 1.36.0 release. As of today the volume is fairly low, but will definitely keep an eye on it.

**Comment by tore-statsig** [comment]
Hmm interesting, this looks like its on the read path for sticky.  Thanks for flagging with us early, we will look into it
